#!/bin/bash

if [[ "$1" = "" ]]; then
  >&2 echo usage: $0 branch-name
  exit 1
fi

TRAVIS_BRANCH=$1 validate/branch-name || exit 1

git checkout master                   || exit 1
git checkout -b $1                    || exit 1

exit 0
