package envvars

import "os"

func setDebugEnvVars() {
	_ = os.Setenv("AWS_ACCESS_KEY_ID", "debug")
	_ = os.Setenv("AWS_CONTAINER_CREDENTIALS_RELATIVE_URI", "debug")
	_ = os.Setenv("AWS_DEFAULT_REGION", "debug")
	_ = os.Setenv("AWS_ENDPOINT", "debug")
	_ = os.Setenv("AWS_REGION", "debug")
	_ = os.Setenv("AWS_SECRET_ACCESS_KEY", "debug")
	_ = os.Setenv("IN_AFFILIATE_WINDOW_API_HOST", "debug")
	_ = os.Setenv("IN_AFFILINET_API_HOST", "debug")
	_ = os.Setenv("IN_BOOKING_API_HOST", "debug")
	// _ = os.Setenv("IN_CI", "debug")
	_ = os.Setenv("IN_GIT_BRANCH", "debug")
	_ = os.Setenv("IN_GIT_SHA", "debug")
	_ = os.Setenv("IN_JWT_SIGNING_KEY", "debug")
	// _ = os.Setenv("IN_LOCAL", "debug")
	_ = os.Setenv("IN_LOG_COLORIZATION", "true")
	_ = os.Setenv("IN_LOG_DEBUG_MESSAGES", "true")
	_ = os.Setenv("IN_LOG_SERIALIZATION", "json-compact")
	_ = os.Setenv("IN_MIGRATIONS_PATH", "debug")
	_ = os.Setenv("IN_NETWORKS_HOST", "debug")
	_ = os.Setenv("IN_NETWORKS_URI", "debug")
	_ = os.Setenv("IN_PGPASSWORD", "debug")
	// os.Setenv("IN_PGPASSWORD_API_HOST", "debug")
	_ = os.Setenv("IN_PGUSER", "debug")
	_ = os.Setenv("IN_PHG_API_HOST", "debug")
	_ = os.Setenv("IN_SFTP_HOST", "debug")
	_ = os.Setenv("IN_SFTP_KEY", "debug")
	_ = os.Setenv("IN_SFTP_PATH_RAKUTEN", "debug")
	_ = os.Setenv("IN_SFTP_PORT", "debug")
	_ = os.Setenv("IN_SFTP_USER", "debug")
	_ = os.Setenv("IN_STACK_NAME", "debug")
	_ = os.Setenv("PGDATABASE", "debug")
	_ = os.Setenv("PGHOST", "debug")
	_ = os.Setenv("PGPASSWORD", "debug")
	_ = os.Setenv("PGPORT", "debug")
	_ = os.Setenv("PGUSER", "debug")
	_ = os.Setenv("POSTGRES_PASSWORD", "debug")
	_ = os.Setenv("POSTGRES_USER", "debug")
}
