#!/bin/bash

http-spec roles/specs/get-debug-pprof.htsf  \
          roles/specs/get-status.htsf       \
          roles/specs/get-role.htsf         \
          roles/specs/get-role-history.htsf || exit 1

exit 0
