#!/bin/bash

for service in $(find . -mindepth 2 -type d -name api -o -name service -o -name worker | egrep -v "(mock|migrator|http-spec|certbot-env)"); do
  echo "${service#./}" || exit 1
done || exit 1

exit 0
