#!/bin/bash

>&2 echo pruning temp images...

docker images              | \
egrep '<none>'             | \
awk '{print $3}'           | \
compatibility/xargs          \
docker rmi -f &> /dev/null || exit 1

exit 0
