#!/bin/bash

>&2 echo deleting dns for $IN_ELB_CNAME...

aws/delete-dns $IN_ELB_CNAME                 \
               CNAME                         \
               $(aws/load-balancer-hostname) \
               300                           || exit 1

exit 0
