#!/bin/bash

>&2 echo transitioning stack...

docker/login                                                  || exit 1
aws/create-repositories                                       || exit 1
docker/push                                                   || exit 1

export IN_VPC_CIDR_BASE=$(aws/vpc-cidr-base-chooser)
export IN_SUBNET_CIDR_BLOCKS=$(aws/subnet-cidr-blocks-chooser)

aws/estimate-stack-cost                                       || exit 1

OUTPUT=$(aws/create-stack 2>&1) && echo "$OUTPUT"             && exit 0 # exit successfully

# TODO these are NOT out-of-order, they're order dependent
export IN_SUBNET_CIDR_BLOCKS=$(aws/subnet-cidr-blocks-getter)
export IN_VPC_CIDR_BASE=$(aws/vpc-cidr-base-getter)

aws/update-stack                                              || exit 1

exit 0
