#!/bin/bash

CHANGE_ID=$1

while true; do
  STATUS=$(
    aws --profile dns \
      route53         \
        get-change    \
          --id $CHANGE_ID | jq --raw-output '.ChangeInfo.Status'
  ) || exit 1

  echo "DNS: $STATUS"

  if [[ "$STATUS" = "INSYNC" ]]; then
    break
  fi

  sleep 10
done || exit 1

exit 0
