#!/bin/bash

HOST=$1

# Create Network
curl $HOST/networks/6                    \
     -X PUT                              \
     -H "Content-Type: application/json" \
     -i                                  \
     -d                                  \
'{
  "name": "Affiliate Window",
  "variant": "affiliate-window",
  "variations": {
    "api-host": "https://api.awin.com",
    "days-per-request": "30",
    "days-to-load": "90",
    "rate-interval": "10s",
    "rate-quantity": "1"
  }
}'

# Create Network Account
curl $HOST/networks/6/accounts/13        \
     -X PUT                              \
     -H "Content-Type: application/json" \
     -i                                  \
     -d                                  \
'{
  "name": "Affiliate Window - UK",
  "variant": "affiliate-window",
  "variations": {
    "additional-id": "12345",
    "currency": "GBP",
    "token": "12345-67890"
  }
}'
