#!/bin/bash

http-spec identities/specs/get-debug-pprof.htsf      \
          identities/specs/get-status.htsf           \
          identities/specs/get-identity.htsf         \
          identities/specs/get-identity-history.htsf || exit 1

exit 0
