FROM scratch
MAINTAINER Loren Hale <loren.hale@gmail.com>

COPY networks-booking-mock-api /
COPY login-response.html       /
COPY response.csv              /

EXPOSE 80

ENTRYPOINT ["/networks-booking-mock-api"]
